### ISSUE TITLE
Question about FFMpeg version used

### ISSUE THREAD

**Issue by wesleyfilleman** [mooncatventures-group/RtspFrames-test#1]
Hello,

Thank you for posting these RTSP demos and source code. This is exactly what I was trying to find for iOS. I do have a question and I suppose bug report or request.

Using the source code, I'm able to view live RTSP streams from IP Cameras but only if they don't require a username or password to access the RTSP stream. If the camera/RTSP stream requires a username/password I've attempted the following format as the address:

rtsp://username:password/xxx.xxx.xxx.xxx/path/to/stream?tcp

Two comments:
- I found that I needed to add "?tcp" at the end, otherwise the default wouldn't stream correctly.
- The HTTP Authentication mechanism doesn't appear to be working.

For both items it appears like these are older FFMpeg issues that was resolved in later builds of FFMpeg which brings me to my real question, what version of FFMpeg was used to build the framework?

I've got the latest 0.11 FFMpeg rebuilt for iOS 5.1 armv7 but I'm looking how to incorporate the libraries into the Framework code. 

How was the FFmpegDecoder.framework built and would it be possible to see that source code or post it as a separate repo to update against the latest FFMpeg builds?

Thanks for taking the time to read and respond. If you'd like you can respond directly to me at: wesleyfilleman@cox.net

Thanks!
Wes

**Comment by ghost** [comment]
How can we get the audio?

**Comment by mooncatventures-group** [comment]
all issues resolved, 0.11 is now included in beta 1, angel coming soon.
audio support in beta 1

**Comment by rdp** [comment]
out of curiosity, any particular commits that had to do with HTTP auth? thanks!

**Comment by mooncatventures-group** [comment]
Not for that code, but all the projects in the repository starting with FFRames-beta1 use a newer version of ffmpeg
that handles authentication better.

ffframes-test is just a simple sample and there are no plans to revise it, it is very similar to frames-beta1.

**Comment by rdp** [comment]
Ok thank you!

**Comment by mooncatventures-group** [comment]
More complete players are AVDemoPlay2l and AVDemoPlayer

You also might want to join our facebook app dev group were there is a lot more information
